import Link from 'next/link'
import TripRealityChecker from '@/components/TripRealityChecker'
import { CHECKER_CITIES } from '@/lib/tripCheckerData'

export const metadata = {
  title: 'India Trip Reality Checker | Explore The City',
  description: 'Check whether your India itinerary is realistic. Find overloaded days, unnecessary transfers and pacing problems before you travel.',
  alternates: { canonical: 'https://www.explorethecity.in/' },
}

export default function Home() {
  return <div>
    <section className="relative overflow-hidden bg-slate-950 pt-36 pb-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(234,88,12,0.35),_transparent_45%)]" /><div className="container-custom relative grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-orange-300 uppercase tracking-[0.25em] text-sm font-bold mb-5">India Trip Reality Checker</p><h1 className="text-5xl md:text-7xl font-extrabold leading-[1.05]">Find the problems before the trip does.</h1><p className="mt-6 text-xl text-gray-300 max-w-2xl">Build one day of your itinerary and see whether the timing, route and pace make sense. No account, no public itinerary and no black-box AI score.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="#checker" className="bg-orange-600 hover:bg-orange-500 px-7 py-4 rounded-lg font-bold">Check my itinerary</Link><Link href="/methodology" className="border border-white/30 hover:bg-white/10 px-7 py-4 rounded-lg font-bold">How scoring works</Link></div></div><div className="rounded-3xl border border-white/15 bg-white/10 p-7 backdrop-blur"><p className="text-sm uppercase tracking-widest text-orange-200 font-bold">Example finding</p><div className="mt-4 flex items-end gap-3"><strong className="text-6xl text-amber-300">62</strong><span className="text-xl font-bold mb-2">/100 · Rushed</span></div><p className="mt-5 text-gray-200">Your plan crosses Jaipur three times and needs about two hours more than a balanced day allows.</p><div className="mt-5 rounded-xl bg-slate-950/60 p-4"><strong>Suggested fix</strong><p className="text-sm text-gray-300 mt-1">Keep Hawa Mahal, City Palace and Jantar Mantar together. Move Amber Fort to a separate morning.</p></div></div></div></section>
    <section id="checker" className="py-20 bg-gradient-to-b from-orange-50 to-white scroll-mt-16"><div className="container-custom"><div className="text-center max-w-3xl mx-auto mb-12"><p className="uppercase tracking-widest text-orange-700 font-bold text-sm">Try it now</p><h2 className="text-4xl md:text-5xl font-extrabold mt-3">Will your day actually work?</h2><p className="mt-4 text-lg text-gray-600">Start with one of five reviewed destinations. Choose stops in the order you intend to visit them.</p></div><TripRealityChecker cities={CHECKER_CITIES} /><p className="text-center mt-10 text-gray-600">Want the full-screen version? <Link href="/trip-checker" className="font-bold text-orange-700 hover:underline">Open the Trip Reality Checker →</Link></p></div></section>
    <section className="py-20 bg-gray-950 text-white"><div className="container-custom"><div className="max-w-3xl"><p className="uppercase tracking-widest text-orange-300 font-bold text-sm">Why this is different</p><h2 className="text-4xl font-extrabold mt-3">A practical check, not another generated list</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3"><div className="rounded-2xl bg-white/5 border border-white/10 p-6"><h3 className="text-xl font-bold">Explains every deduction</h3><p className="mt-2 text-gray-400">The report shows which rule fired, why it matters and how to fix the day.</p></div><div className="rounded-2xl bg-white/5 border border-white/10 p-6"><h3 className="text-xl font-bold">Keeps plans private</h3><p className="mt-2 text-gray-400">The guided checker runs in your browser and never creates an indexable result page.</p></div><div className="rounded-2xl bg-white/5 border border-white/10 p-6"><h3 className="text-xl font-bold">Admits what it cannot know</h3><p className="mt-2 text-gray-400">Travel estimates are conservative, not live. Current access and opening information must still be verified.</p></div></div></div></section>
    <section className="py-20 bg-white"><div className="container-custom grid gap-10 lg:grid-cols-2 lg:items-center"><div><h2 className="text-4xl font-extrabold">Five destinations at launch</h2><p className="mt-4 text-lg text-gray-600">The checker supports Bangalore, Mumbai, Goa, Delhi and Jaipur. We add destinations only after their planning data is structured and reviewed.</p><div className="mt-6 flex flex-wrap gap-2">{CHECKER_CITIES.map((city) => <span key={city.slug} className="rounded-full bg-orange-50 border border-orange-200 px-4 py-2 font-semibold text-orange-900">{city.name}</span>)}</div></div><div className="rounded-2xl bg-orange-50 border border-orange-100 p-8"><h3 className="text-2xl font-bold">Know something has changed?</h3><p className="mt-3 text-gray-700">Opening arrangements, access and transport conditions change. Tell us which destination and place needs correction; we review reports before updating the tool.</p><Link href="/contact" className="inline-block mt-5 font-bold text-orange-700 hover:underline">Send a correction →</Link></div></div></section>
  </div>
}
